//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIACinemaDBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public decimal room { get; set; }
        public string IMDB_id { get; set; }
        public string email { get; set; }
        public int seat_no { get; set; }
        public System.DateTime date_time { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
