//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIACinemaDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reservation_id { get; set; }
        public int seat_no { get; set; }
        public Nullable<int> schedule_id { get; set; }
        public Nullable<int> person_id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
